version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ranking_user
      POSTGRES_PASSWORD: ranking_password
      POSTGRES_DB: ranking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ranking_user -d ranking_db"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: